import Foundation

/// Generates AppleScript code for accessibility element interaction
@MainActor
class AppleScriptGenerator {
    // MARK: - Types
    
    /// Style of script generation
    enum ScriptStyle {
        case systemEvents    // Uses System Events
        case axElement       // Uses AX Elements directly
    }
    
    /// Script generation options
    struct Options {
        var includeComments = true
        var includeErrorHandling = true
        var useNumericIndices = false
        var style: ScriptStyle = .systemEvents
        var waitForElement = true
        var timeout: TimeInterval = 5.0
    }
    
    // MARK: - Properties
    
    /// Shared instance
    static let shared = AppleScriptGenerator()
    
    /// Current generation options
    var options = Options()
    
    // MARK: - Script Generation
    
    /// Generate script for accessing current element
    func generateScript(for element: AccessibleElement) async throws -> String {
        var script = ""
        
        // Add header comment
        if options.includeComments {
            script += "-- Generated by UI Browser 4\n"
            script += "-- Target: \(await element.processName() ?? "Unknown")\n"
            script += "-- Element: \(element.AXRole ?? "Unknown") - \(element.AXTitle ?? "")\n\n"
        }
        
        // Add tell block based on style
        switch options.style {
        case .systemEvents:
            script += try await generateSystemEventsScript(for: element)
        case .axElement:
            script += try await generateAXElementScript(for: element)
        }
        
        return script
    }
    
    /// Generate script using System Events
    private func generateSystemEventsScript(for element: AccessibleElement) async throws -> String {
        var script = ""
        
        // Get process info
        let processName = await element.processName() ?? "Unknown"
        
        // Start tell block
        script += "tell application \"System Events\"\n"
        
        // Add error handling if enabled
        if options.includeErrorHandling {
            script += """
                try
                    set timeoutSeconds to \(options.timeout)
                    set endTime to (current date) + timeoutSeconds
                    
                    repeat
                        if (current date) > endTime then
                            error "Timeout waiting for process"
                        end if
                        
                        if exists process "\(processName)" then
                            exit repeat
                        end if
                        
                        delay 0.1
                    end repeat
                    
            """
        }
        
        // Add process selection
        script += "    tell process \"\(processName)\"\n"
        
        // Generate element path
        let path = try await generateElementPath(for: element)
        script += path.indented(by: 2)
        
        // Add element interaction
        if let role = element.AXRole?.lowercased() {
            switch role {
            case "button":
                script += "\n        click \(path.lastComponent)\n"
            case "textfield", "textbox":
                script += "\n        set value of \(path.lastComponent) to \"<value>\"\n"
            case "checkbox", "radio button":
                script += "\n        click \(path.lastComponent)\n"
            case "menu", "menuitem":
                script += "\n        click \(path.lastComponent)\n"
            default:
                if options.includeComments {
                    script += "\n        -- TODO: Add interaction for \(role)\n"
                }
            }
        }
        
        // Close tell blocks
        script += "    end tell\n"
        script += "end tell\n"
        
        return script
    }
    
    /// Generate script using AX Elements directly
    private func generateAXElementScript(for element: AccessibleElement) async throws -> String {
        var script = ""
        
        // Add error handling if enabled
        if options.includeErrorHandling {
            script += """
                use framework "AppKit"
                use scripting additions
                
                on findElement(pid, searchPath)
                    tell application "System Events"
                        set startTime to current date
                        repeat
                            try
                                set elem to first UI element of process id pid whose value of attribute "AXPath" is searchPath
                                return elem
                            on error
                                if ((current date) - startTime) > \(options.timeout) then
                                    error "Timeout finding element"
                                end if
                                delay 0.1
                            end try
                        end repeat
                    end tell
                end findElement
                
            """
        }
        
        // Get process info
        let pid = await element.pid()
        let path = try await element.elementPath()
        
        script += """
        set pid to \(pid)
        set searchPath to "\(path)"
        
        set targetElement to findElement(pid, searchPath)
        
        """
        
        // Add element interaction
        if let role = element.AXRole?.lowercased() {
            switch role {
            case "button":
                script += "tell targetElement to perform action \"AXPress\"\n"
            case "textfield", "textbox":
                script += "set value of attribute \"AXValue\" of targetElement to \"<value>\"\n"
            case "checkbox", "radio button":
                script += "tell targetElement to perform action \"AXPress\"\n"
            case "menu", "menuitem":
                script += "tell targetElement to perform action \"AXPress\"\n"
            default:
                if options.includeComments {
                    script += "-- TODO: Add interaction for \(role)\n"
                }
            }
        }
        
        return script
    }
    
    /// Generate element path description
    private func generateElementPath(for element: AccessibleElement) async throws -> ElementPath {
        var path = ElementPath()
        var current: AccessibleElement? = element
        
        // Build path from element back to root
        while let elem = current {
            // Get element attributes
            let role = elem.AXRole ?? "unknown"
            let title = elem.AXTitle
            let index = await elem.siblingIndex()
            
            // Create path component
            var component = role.lowercased()
            if let title = title {
                component += " \"\(title)\""
            }
            if options.useNumericIndices {
                component += " \(index)"
            }
            
            path.components.insert(component, at: 0)
            
            // Move to parent
            current = elem.AXParent
        }
        
        return path
    }
}

/// Helper for building element paths
struct ElementPath {
    var components: [String] = []
    
    var lastComponent: String {
        components.last ?? ""
    }
    
    func indented(by spaces: Int) -> String {
        let indent = String(repeating: " ", count: spaces)
        return components.joined(separator: "\n\(indent)")
    }
}