import Foundation

/// Manages AppleScript code templates and generation
@MainActor
final class AppleScriptTemplateManager {
    // MARK: - Types
    
    /// Script template type
    enum TemplateType {
        case systemEvents    // Uses System Events
        case axElement       // Direct AX API access
        case hybrid         // Mixed approach
        case uiautomation   // XCTest UI Automation
    }
    
    /// Code generation style
    struct GenerationStyle {
        var includeComments: Bool = true
        var useNumericIndices: Bool = false
        var indentWithTabs: Bool = false
        var addErrorHandling: Bool = true
        var addLogging: Bool = false
        var waitForElements: Bool = true
        var timeout: TimeInterval = 5.0
    }
    
    /// Script section
    struct ScriptSection {
        let name: String
        let template: String
        let variables: [String: String]
        let condition: (() -> Bool)?
    }
    
    // MARK: - Properties
    
    /// Shared instance
    static let shared = AppleScriptTemplateManager()
    
    /// Template cache
    private var templateCache: [TemplateType: [String: String]] = [:]
    
    /// Custom templates
    private var customTemplates: [String: String] = [:]
    
    // MARK: - Template Management
    
    /// Load built-in templates
    private func loadBuiltInTemplates() {
        // System Events templates
        templateCache[.systemEvents] = [
            "header": """
                -- Generated by UI Browser 4
                -- Target: {targetName}
                -- Date: {date}
                -- Description: {description}
                
                use scripting additions
                
                property timeoutSeconds : {timeout}
                property waitInterval : 0.1
                
                """,
            
            "tell_block": """
                tell application "System Events"
                    {content}
                end tell
                """,
            
            "wait_block": """
                -- Wait for process
                set endTime to (current date) + timeoutSeconds
                repeat
                    if (current date) > endTime then
                        error "Timeout waiting for process"
                    end if
                    
                    if exists process "{processName}" then
                        exit repeat
                    end if
                    
                    delay waitInterval
                end repeat
                """,
            
            "element_reference": """
                {role} "{name}" of {parent}
                """,
            
            "element_search": """
                set targetElement to first {role} of {parent} where its {attribute} is "{value}"
                """,
            
            "action_press": """
                click {element}
                """,
            
            "action_set": """
                set value of {element} to "{value}"
                """,
            
            "error_handler": """
                try
                    {content}
                on error errorMessage
                    display dialog errorMessage buttons {"OK"} default button 1 with icon stop
                    return
                end try
                """
        ]
        
        // AX Element templates
        templateCache[.axElement] = [
            "header": """
                -- Generated by UI Browser 4
                -- Target: {targetName}
                -- Date: {date}
                -- Description: {description}
                
                use framework "AppKit"
                use scripting additions
                
                property timeoutSeconds : {timeout}
                property waitInterval : 0.1
                
                on findElement(pid, searchPath)
                    tell application "System Events"
                        set startTime to current date
                        repeat
                            try
                                set elem to first UI element of process id pid whose value of attribute "AXPath" is searchPath
                                return elem
                            on error
                                if ((current date) - startTime) > timeoutSeconds then
                                    error "Timeout finding element"
                                end if
                                delay waitInterval
                            end try
                        end repeat
                    end tell
                end findElement
                
                """,
            
            "element_lookup": """
                set pid to {pid}
                set searchPath to "{path}"
                set targetElement to findElement(pid, searchPath)
                """,
            
            "action_press": """
                tell targetElement to perform action "AXPress"
                """,
            
            "action_set": """
                set value of attribute "AXValue" of targetElement to "{value}"
                """
        ]
        
        // Hybrid templates
        templateCache[.hybrid] = [
            "header": """
                -- Generated by UI Browser 4
                -- Target: {targetName}
                -- Date: {date}
                -- Description: {description}
                
                use framework "AppKit"
                use scripting additions
                
                property timeoutSeconds : {timeout}
                property waitInterval : 0.1
                
                """,
            
            "system_events_block": """
                tell application "System Events"
                    {content}
                end tell
                """,
            
            "ax_element_block": """
                -- Direct AX access
                set targetElement to current application's NSWorkspace's sharedWorkspace()'s frontmostApplication's |window|'s accessibilityElement()
                """
        ]
        
        // UI Automation templates
        templateCache[.uiautomation] = [
            "header": """
                import XCTest
                
                class {testName}: XCTestCase {
                    func test{functionName}() throws {
                        let app = XCUIApplication()
                        app.launch()
                        
                """,
            
            "element_lookup": """
                let element = app.{type}["{identifier}"]
                XCTAssert(element.waitForExistence(timeout: {timeout}))
                """,
            
            "action_tap": """
                element.tap()
                """,
            
            "action_type": """
                element.typeText("{text}")
                """
        ]
    }
    
    /// Load custom templates
    private func loadCustomTemplates() {
        guard let url = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first?
                .appendingPathComponent("UI Browser 4")
                .appendingPathComponent("Templates") else {
            return
        }
        
        do {
            let files = try FileManager.default.contentsOfDirectory(at: url, includingPropertiesForKeys: nil)
            for file in files where file.pathExtension == "applescript" {
                let name = file.deletingPathExtension().lastPathComponent
                let content = try String(contentsOf: file)
                customTemplates[name] = content
            }
        } catch {
            print("Error loading custom templates: \(error)")
        }
    }
    
    /// Get template for type
    func template(for type: TemplateType, name: String) -> String? {
        templateCache[type]?[name]
    }
    
    /// Get custom template
    func customTemplate(named name: String) -> String? {
        customTemplates[name]
    }
    
    /// Save custom template
    func saveCustomTemplate(_ template: String, named name: String) throws {
        guard let url = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first?
                .appendingPathComponent("UI Browser 4")
                .appendingPathComponent("Templates") else {
            return
        }
        
        try FileManager.default.createDirectory(at: url, withIntermediateDirectories: true)
        try template.write(to: url.appendingPathComponent("\(name).applescript"), atomically: true, encoding: .utf8)
        
        customTemplates[name] = template
    }
    
    // MARK: - Code Generation
    
    /// Generate script sections
    func generateSections(
        for element: AccessibleElement,
        type: TemplateType,
        style: GenerationStyle
    ) async throws -> [ScriptSection] {
        var sections: [ScriptSection] = []
        
        // Add header
        sections.append(try await generateHeader(for: element, type: type, style: style))
        
        // Add wait block if needed
        if style.waitForElements {
            sections.append(try await generateWaitBlock(for: element, type: type, style: style))
        }
        
        // Add element lookup
        sections.append(try await generateElementLookup(for: element, type: type, style: style))
        
        // Add action
        if let actionSection = try await generateAction(for: element, type: type, style: style) {
            sections.append(actionSection)
        }
        
        return sections
    }
    
    /// Generate complete script
    func generateScript(
        for element: AccessibleElement,
        type: TemplateType,
        style: GenerationStyle
    ) async throws -> String {
        var script = ""
        
        // Generate sections
        let sections = try await generateSections(for: element, type: type, style: style)
        
        // Build script
        for section in sections {
            guard section.condition?() ?? true else { continue }
            
            let content = interpolate(section.template, with: section.variables)
            script += content + "\n\n"
        }
        
        // Add error handling if needed
        if style.addErrorHandling {
            script = wrapWithErrorHandler(script, type: type)
        }
        
        return script
    }
    
    // MARK: - Section Generation
    
    private func generateHeader(
        for element: AccessibleElement,
        type: TemplateType,
        style: GenerationStyle
    ) async throws -> ScriptSection {
        let formatter = DateFormatter()
        formatter.dateStyle = .medium
        formatter.timeStyle = .medium
        
        return ScriptSection(
            name: "Header",
            template: template(for: type, name: "header") ?? "",
            variables: [
                "targetName": await element.processName() ?? "Unknown",
                "date": formatter.string(from: Date()),
                "description": element.description,
                "timeout": String(format: "%.1f", style.timeout)
            ],
            condition: nil
        )
    }
    
    private func generateWaitBlock(
        for element: AccessibleElement,
        type: TemplateType,
        style: GenerationStyle
    ) async throws -> ScriptSection {
        return ScriptSection(
            name: "Wait",
            template: template(for: type, name: "wait_block") ?? "",
            variables: [
                "processName": await element.processName() ?? "Unknown"
            ],
            condition: { style.waitForElements }
        )
    }
    
    private func generateElementLookup(
        for element: AccessibleElement,
        type: TemplateType,
        style: GenerationStyle
    ) async throws -> ScriptSection {
        switch type {
        case .systemEvents:
            return ScriptSection(
                name: "Element Lookup",
                template: template(for: type, name: "element_reference") ?? "",
                variables: [
                    "role": element.AXRole ?? "UI element",
                    "name": element.AXTitle ?? "",
                    "parent": "window 1"
                ],
                condition: nil
            )
            
        case .axElement:
            return ScriptSection(
                name: "Element Lookup",
                template: template(for: type, name: "element_lookup") ?? "",
                variables: [
                    "pid": String(await element.pid()),
                    "path": try await element.elementPath()
                ],
                condition: nil
            )
            
        case .hybrid:
            // Choose best approach based on element
            let useSystemEvents = element.AXRole == "AXWindow" || element.AXRole == "AXMenuBar"
            return try await generateElementLookup(
                for: element,
                type: useSystemEvents ? .systemEvents : .axElement,
                style: style
            )
            
        case .uiautomation:
            return ScriptSection(
                name: "Element Lookup",
                template: template(for: type, name: "element_lookup") ?? "",
                variables: [
                    "type": element.AXRole?.lowercased() ?? "element",
                    "identifier": element.AXIdentifier ?? element.AXTitle ?? "",
                    "timeout": String(format: "%.1f", style.timeout)
                ],
                condition: nil
            )
        }
    }
    
    private func generateAction(
        for element: AccessibleElement,
        type: TemplateType,
        style: GenerationStyle
    ) async throws -> ScriptSection? {
        // Determine action based on role
        let role = element.AXRole?.lowercased() ?? ""
        let template: String?
        let variables: [String: String]
        
        switch role {
        case "button", "menuitem", "checkbox", "radio button":
            template = template(for: type, name: "action_press")
            variables = ["element": "targetElement"]
            
        case "textfield", "textbox":
            template = template(for: type, name: "action_set")
            variables = [
                "element": "targetElement",
                "value": "<value>"
            ]
            
        default:
            return nil
        }
        
        return ScriptSection(
            name: "Action",
            template: template ?? "",
            variables: variables,
            condition: nil
        )
    }
    
    // MARK: - Helpers
    
    private func interpolate(_ template: String, with variables: [String: String]) -> String {
        var result = template
        for (key, value) in variables {
            result = result.replacingOccurrences(of: "{\(key)}", with: value)
        }
        return result
    }
    
    private func wrapWithErrorHandler(_ script: String, type: TemplateType) -> String {
        guard let template = template(for: type, name: "error_handler") else {
            return script
        }
        
        return interpolate(template, with: ["content": script])
    }
}